server:
  port: 8099
spring:
  application:
    name: xyhs-tradecenter
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  profiles:
    active: dev
  resources:
     static-locations: classpath:/resources/
mybatis-plus:
   configuration:
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl