spring:
############# 新注册注册consul 配置################
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        hostname: ${spring.cloud.client.ip-address}
        service-name: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        health-check-critical-timeout: 20s
        tags: version=1.0.0,name=gateway
  datasource:
    url: jdbc:mysql://182.61.42.210:3306/basecenter?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Ljp10061087@
    type: com.alibaba.druid.pool.DruidDataSource

